### ISSUE TITLE
KeyError: 'U' returned from `CDG.predict()`

### ISSUE THREAD

**Issue by taylorreiter** [magarveylab/NLPPrecursor#7]
Hello! I'm interested in using NLPPrecursor to scan for RIPPs. When I was testing this on the human transcriptome, I encountered a KeyError. Do you know what causes this error/what the 'U' stands for? Information to reproduce the error is below.

Models downloaded from: https://github.com/magarveylab/NLPPrecursor/releases/download/1.0/nlpprecursor_models.tar.gz

Minimum reproducible example (assuming models in the `models` directory):
```
from nlpprecursor.classification.data import DatasetGenerator as CDG
from pathlib import Path
import nlpprecursor
import sys
# This allows for backwards compatibility of the pickled models.
sys.modules["protai"] = nlpprecursor

models_dir = Path("models") # downloaded from releases! 

class_model_dir = models_dir / "classification"
class_model_path = class_model_dir / "model.p"
class_vocab_path = class_model_dir / "vocab.pkl"
annot_model_dir = models_dir / "annotation"
annot_model_path = annot_model_dir / "model.p"
annot_vocab_path = annot_model_dir / "vocab.pkl"

sequences = [
    {
        "sequence": "MCAARLAAAAAAAQSVYAFSARPLAGGEPVSLGSLRGKVLLIENVASLUGTTVRDYTQMNELQRRLGPRGLVVLGFPCNQFGHQENAKNEEILNSLKYVRPGGGFEPNFMLFEKCEVNGAGAHPLFAFLREALPAPSDDATALMTDPKLITWSPVCRNDVAWNFEKFLVGPDGVPLRRYSRRFQTIDIEPDIEALLSQGPSCA",
        "name": "unique_name",
    }
]

class_predictions = CDG.predict(class_model_path, class_vocab_path, sequences)
```

Error:
```
| 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/ubuntu/miniconda3/envs/nlpprecursor/lib/python3.7/site-packages/nlpprecursor/classification/data.py", line 274, in predict
    tok_ids = vocab.numericalize([x for x in orf['sequence']])
  File "/home/ubuntu/miniconda3/envs/nlpprecursor/lib/python3.7/site-packages/nlpprecursor/classification/transform.py", line 78, in numericalize
    return np.asarray([stoi[w] for w in t])
  File "/home/ubuntu/miniconda3/envs/nlpprecursor/lib/python3.7/site-packages/nlpprecursor/classification/transform.py", line 78, in <listcomp>
    return np.asarray([stoi[w] for w in t])
KeyError: 'U'
```

Environment:
```
channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - python=3.7
   - biopython=1.79
   - pip=24.0
   - pip:
     - torch==1.0.0
     - git+https://github.com/nishanthmerwin/fastai.git@deepripp_install
     - git+https://github.com/magarveylab/nlpprecursor
```

**Comment by taylorreiter** [comment]
Investigating the classification model pickle file, I see:
```
import pickle
with open(class_vocab_path, 'rb') as f:
    data = pickle.load(f)
 
print(data.itos)
{0: 'M', 1: 'A', 2: 'N', 3: 'F', 4: 'D', 5: 'L', 6: 'V', 7: 'Q', 8: 'K', 9: 'S', 10: 'G', 11: 'Y', 12: 'T', 13: 'C', 14: 'R', 15: 'H', 16: 'I', 17: 'P', 18: 'E', 19: 'W', 20: 'X'}
```

which means the two non standard amino acids selenocysteine and pyrrolysine are not included. I'll write a small script to filter these out!

**Comment by nishanthmerwin** [comment]
Yeah, looks like you solved the issue yourself! 
We definitely did not train the model on non-standard amino acids, although we did include X for ambiguous amino acids (typically from poor sequencing). In your source dataset you _could_ convert the U and O to an X to get a prediction however I'm not really sure how accurate the model would be in those cases.
